language: ruby
cache: bundler
install:
- bundle install
script:
  - "./build.sh"
  - "./htmltest.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: i9LmdFCgCex33PxN0WWpVWEQvm7O5QfBMFR+LRt0KlzpEdjS0AbmYQKi2xuwm0Xx0NQ+7lCKWe9Nj2T8DS23chjVNLcQa/cTFKlBhJ2PjAAQxST1xHj6zpnjQAbasvVsk/jymy7csss7G8OAGlGg/qViL50SQ8IuOcEUGoj2vKKlEBf8cxQwxRSFRYR/S1c+pVJQy7KUQEl4skKuMD/sRa3WfiJJUXy/Bto96lUCYCYd0QDBbpq2T45sJTvgMlfPIv0Iho/RZ9MFhvNIHWY518bRnhdnbZ9Gp+8Ta8NvpfVKm/mDIkr5YDRPINbj6zwkfl5ah9o/Fhl/LxyYZc6nDc3b09ZSofcFZ4/8EYUrH/X7faTkiGW4vp6eqKq/MZBQXEgWoOQg9RQbyvXBZyy9ssVifa1tRvmF25J7fP/2UNuS76109EA3j0fLSZKsre+SskuD6mELWKrQSFYFZFvtR7O2/E8w6FAXvFc/QwYZbUHJmdqbUtsP/xzHplHbYUeHIjy+uGctIlXV3wtjeHF76PV103jUuJpoH/uUofmfLmiAN4RuTH/MdsmQ6WM+aopCrh3NNbUj+t/auiauFXSY71Nx+RlGy6+proS4DXb7YtI1qDJLurrYQ5YtOTnBGTdLBQVjM/OT9HNUHGEqSdiDSMZebAN6KUdSptMPGqIA13A=