language: ruby
cache: bundler
install:
- bundle install
script:
- "./build.sh"
branches:
  only:
  - master
env:
  global:
    secure: n0PUrlkq7XmVD4/CM3slPo+d9ErKWBx8QRHMBcOXgJAbXEp6rb0OozlKEvByrkQC1XWyOakcHoOiwDykh5eRh3tRYdEBm23zPZqi5n+iPoq+laSuGJkyUv+vhWCuzZ+iJW/1YkuErm2OAFVBjA5HonivqF3TJh3eDU1b1tsaFP+ycvbqCjPcgAynw8mNGa9NZQNiLUQ7SGRgf60agraINSHCFBwpw7pePIws+MAZWQNnEiBvHiEEszGsHi0DxMy0zNe+YuL/i2YuzzYqI6n8WD4O0p6Mvvs9mbvjC5/VltEs4OMnb7AHLd5oFJA2Ph6sV8AO14P3Fccr1eIXc/CvMhiIcTFvKkteN7zNWCaI09h+8jtAFpBVNNVjCvcxAIisVzlfntxx2POztB8HoJzw1Ujm9pNXKT/JP36pwk9CYl+ZgFKI7EIWydpeONlwLCeuSrSiJ5+aDm6ZfJryrz5gWR1Ul4lr8bmX1m4KpgQlX1bxg4iapuJJK8GYklN2Glhe3zMlB/ZutF8VLgamTL8UJO0HxiizPxSS+syRGuKHpp1K0S32pRRbWhQ6G6JmNx+EkXWItSueXUbalDxs5Y+L0SBHB1qpD82MzU5FKFp+dBUEK5tDl7AaxInl/b5JDNdyVhyU5L/qRbozd5Q4+A51AkLS39on5O12lmLaYNIkho4=
