language: ruby
cache: bundler
install:
- bundle install
script:
- "./build.sh"
branches:
  only:
  - master
env:
  global:
    secure: HIazA3dX8EISLmSSpQdk0wNfIx1XTUFRiRrRAroxcsDqLJjrlOyUwShreru86DN8EiQ9xPS7dz89nK3byqos8vf6vrbcElRVILAxKrmkz3Wz/BecGg8zfUlKlB0QQ0zgQtzKqt1iBMYiwlaXt2okTq8mRQv4yiBBvNHA04A15jc=
