language: ruby
cache: bundler
install:
- bundle install
script:
- "./build.sh"
branches:
  only:
  - master
env:
  global:
  - secure: aboIAdqGY7rmG3ZCg1FueC8xRrwlD17zFMu1DkUZa41jdeNxt7HD3ORs1L3XStPCAGwJqDryj2rA+x96Otiy859664ehdtVdZLiq6GX0/zkeBPdGVFBGN2O8w2WPCilfH8G9JSZkoRUTjfQJAgWTt7tUx79j6K7oB+iYQxPRVeE=
