name: Mindless Rambling Nonsense
markdown: kramdown
highlighter: rouge
description: My thoughts are mindless and rambling so the best place for them is the internet
url: http://pauldambra.github.io
author: Paul D'Ambra
plusProfile: https://plus.google.com/114260096260757534167?rel=author
excerpt_separator: <!--more-->
exclude: ['Guardfile', .gitgnore', '.ruby-version', 'build.sh', 'Gemfile', 'Gemfile.lock', 'README.md']
ampdir: amp
facebook_id: 1029758320473951
amp_googleanalytics_id: UA-49969634-2
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      header_class: "hero"
