name: Mindless Rambling Nonsense
markdown: redcarpet
highlighter: pygments
description: My thoughts are mindless and rambling so the best place for them is the internet
url: http://pauldambra.github.io
plusProfile: https://plus.google.com/114260096260757534167?rel=author
